### ISSUE TITLE
Port e2e updates from RC Operator

### ISSUE THREAD

**Issue by edavidj** [OpenLiberty/open-liberty-operator#156]
Migrate some of the e2e test updates over from the RC operator

- [x] Knative test updates ([#108](https://github.com/application-stacks/runtime-component-operator/pull/108))
- [x] Imagestream test
- [x] Cert Manager test
  - Note: Improvements to this are in progress, but port what's already there for now
- [x] Updates from [#77](https://github.com/application-stacks/runtime-component-operator/pull/77), this will be merged into RC later this week but can begin porting now.
- [x] Port changes that allow for running Minishift jobs as well as OCP ([#104](https://github.com/application-stacks/runtime-component-operator/pull/104))
