### ISSUE TITLE
Sync up with RCO

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#267]
- [x] Remove embedded Certificates - https://github.com/application-stacks/runtime-component-operator/issues/171
- [x] Remove integration/reference to kAppNav - https://github.com/application-stacks/runtime-component-operator/issues/172
- [x] Remove spec.architecture parameter. We already have spec.affinity.architecture, which should be used instead. https://github.com/application-stacks/runtime-component-operator/issues/241
